# Generated by Django 2.0.4 on 2018-04-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myRoom', models.CharField(max_length=20)),
                ('myStatus', models.BooleanField(default=0)),
            ],
        ),
    ]
