# Generated by Django 2.0.4 on 2018-04-19 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomReservations', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomStatus',
        ),
    ]
